---
title: 読書メモ：Trinh (2024)
author:
  - name: Shingo Nitta
    corresponding: true
    email: 20249157@gakushuin.ac.jp
    affiliations:
      - name: Japan Society for the Promotion of Science
      - name: Gakushuin University
date: 2024/10/26
format: html
categories:
  - Readings
  - Social Inequality
  - Quantitative Method
  - Gender
  - Wealth
execute: 
  echo: false
---

:::{.callout}
## 購読文献

Trinh, Nhat An. 2024. “Class Origin, Intergenerational Transfers, and the Gender Wealth Gap.” *Socio-Economic Review* mwae054. doi: 10.1093/ser/mwae054.

:::

# 要約

## イントロダクション

女性は男性よりも平均して資産額が少ない。その理由として、先行研究では女性の労働市場への参入や収入、金融行動(financial behavior)を取り上げてきた。しかし、男女差を生み出す出身階層の役割については十分に関心が当てられていない。そこで本研究では、出身階層とジェンダーとの視点から男女間資産格差について、(1) 男女間資産格差は出身階層によってどのように異なるのか、(2) 男女間での世代間移転の格差は出身階層によってどのように異なるのか、(3) 世代内移転を平等化すると、出身階層による男女間資産格差は減るのか、という問いにSOEP(ドイツのパネルデータ)を用いて答えることで明らかにする。

## 先行研究

ドイツでは男女間資産格差はおよそ30000ユーロ(日本円で480万円ほど)、24~28\%の差がある。その差は労働市場での勤労所得と職業の違いによって説明されてきた。また、投資という観点でも、女性は男性よりもリスクを取らないことが知られている(not conclusiveだが)。そのほか、家族形成に影響の男女での違いもまた資産蓄積に関連している。

## 出身階層によるばらつきと世代間移転の役割

出身階層として、本研究は出身階層として職業(階級)に着目する。親の職業(階級)はその子(つまり本人)の収入や貯蓄行動に影響する側面と、親から子への資産移転に影響する側面がある。そして、後者の移転は本人のジェンダーによってその程度や機会が異なるだろう。というのも、職業(階級)が異なる親は男性性・女性性にたいする理想が異なり、また異なる社会的再生産戦略[^1]が資産移転に男女差を生むためである。この点で、経済的資本と文化資本の両方が重要となる。さらに、経済的資本と文化資本の垂直的な差異、すなわち資本の総量と水平的な差異、すなわち資本の構成とを区別する。

[^1]: 女子より男子に高階層を期待する、など？本文中には説明がない。

低階層と比べて高階層の家族では、より男子に多く資産を移転することが想定される。なぜなら、高階層の家族は保守的な規範と伝統的なジェンダー役割を有しており、また、事業や住宅資産のような男子に移転しやすい資産を多く持っているためである。そして、そもそも高階層の家族の方が資産を移転しやすい。結果的に、より高階層の家族で世代間移転は男性でより多いことが想定される。

経済資本が資本構成の大部分を占める家族は、社会的再生産戦略としてその金融・事業・経営体を世代にわたって維持するために、関連部門や産業で雇用したり、直接事業や経営体を渡したりする。同時に、教育面でも再生産するために、子どもに教育投資をする。このような文化的な移転は男女間であまり差はない。

## ドイツの文脈

ドイツでは生前贈与と遺産相続では異なる規制が適用される：生存贈与には規制はないが、遺産相続にはすべての相続人が相続額の50\%を受け取る権利を持つ。このため、生前贈与では男女間での格差が生じやすく、そしてそれは高階層の家族や経済資本が構成上支配的な家族でより顕著にみられるだろう。また、贈与がライフコース初期(学齢期など)で起これば相続よりも資産の蓄積に男女差が生じやすいことも想定される。

ドイツでは400000ユーロ(6500万円くらい)には徴税されず、さらに不動産や土地、事業はさらに除外される。そのため、そうした資産を持っている人はより税負荷がより軽くなる。このような税の低さが世代間移転の男女差をさらに促進させる。規制それ自体はドイツ特有だが、相続や贈与の分布と特定の資産の授受についての男女差は多くの国でも適用できるだろう。

## データと方法

### データ

SOEP。2002年から2017年までのデータをプールし、欠損と外れ値を取り除き、66823人の観察を得た。

### 変数

- **個人資産**：資産-負債。インフレーション調整済み。

- **出身階層**：子が15歳のときの親の職業(階級)。Oesch(2006)の分類を用いる。

- **世代間移転**：かつて受け取った資産の額とタイプ、年次。インフレーション調整済み。

### 方法

- 資産の絶対的な差異($\text{男性の平均資産額} - \text{女性の平均資産額}$)と相対的差異($\text{男性の平均資産額} / (\text{男性の平均資産額} + \text{女性の平均資産額})$)を算出。

- 相続や贈与を受け取る確率とこれまで受けた資産の累積額の平均値の男女差を出身階層別に比較する。

- 世代間移転の**確率**を無作為化する＝各出身階層内で観察された移転の分布と構造があらかじめ保存されるように実施される。つまり、各回答者の世代間移転を、そのタイプ、額、構成などは変更せず、同じ階層出身の回答者間で無作為に再配分する（男女格差をなくす）。

- gap-closing estimandを推定する：はじめに、OLS推定による各出身階層内の実際の資産格差を算出し、次いで無作為化した世代間移転の額を用いて資産を予測する。

## 結果

1. 出身階層とジェンダーによって資産の額は層化されており高階層ほど資産額は多く、男性より女性で資産額は少ない。出身階層の上層でジェンダー格差がことに大きい。

2. 受領確率も高階層でよりたかいこと、贈与より相続の方が受領しやすいこと、男女差は統計的有意ではない。

3. 累積移転額も層化されているが、ジェンダー差は確認されない。

4. Large employerでの平等化効果が大きく、それ以外ではほとんど平等化効果は見られない。

## 議論

- 経済資本より文化資本が支配的な階層においては男女差はほとんど確認されない→中産階級にとっては世代間移転は資産のソースにはならないことを示唆

- 移転を受け取る確率は予想と反して男女差はみられなかった→世代間移転が資産の男女格差を説明しない

- 移転を無作為化した反実仮想分析において、large employer familiesでは40\%ほどの男女差が縮まったが、それ以外ではほとんど変化がなかった

  - 総合的に鑑みて、世代間移転が資産の男女格差をもたらす程度は超高階層においてのみ確認される
