---
title: "Education Sets the Stage, Sex Draws the Pathway"
subtitle: "Occupational Skill Allocation over the Life Course in Japan"
date: 2023-11-17
author:
  - name: Shingo Nitta
    url: "https://shingonitta.com/"
    affiliation: Gakushuin University
categories:
  - Life Course
  - Occupation
  - Task/Skill
status: work-in-progress
pub-info:
  links:
    # - name: Working Paper
    #   url: "yanagimoto_why_2023.pdf"
    #   local: true
    #   icon: fa-solid fa-file-pdf
    # - name: Slides (SEHO2023)
    #   url: "seho2023_yanagimoto.pdf"
    #   local: true
    #   icon: fa-solid fa-chalkboard-user
hide-detail: true
pub-status: 
  # status: Writing
  # class: warning
  # icon: fa-solid fa-pencil
  # status: Under review
  # class: success
  # icon: fas fa-glasses
---

<!-- [{{< fa file-pdf >}} Working Paper](yanagimoto_why_2023.pdf) &nbsp;
[ {{< fa chalkboard-teacher >}} Slides (SEHO2023)](seho2023_yanagimoto.pdf) -->

## Abstract

Occupational allocation over the life course matters for inequality in the labor market. This study considers the long-term occupational ‘skill’ trajectory by education and sex. Using nationally representative retrospective data in Japan, the occupational skill level declined around pensionable age, but the degree of decline depends on one’s sex/education and the type of skills. Education matters for skill maintenance over the life course, and gender matters skill accumulation in early life and equalization in later life, except quantitative and engineering skills. I argue that inequality-generating process over the life course can be combined in one’s different life stages by investigating multidimensional career pathways through occupational skills.

