---
title: "スキル指標の標準化と解釈に関するメモ"
date: 2022-04-04
author: 新田真悟
categories:
  - Data Analysis
  - Japanese Onet
---

# はじめに

最近、日本版O-NET（以下、たんにO-NET）を用いた研究プロジェクトに取り組んでいます。O-NETでは各職業に求められるスキル要件や各職業の仕事の性質、仕事の内容などを職業間で比較可能な形式で尋ねています。それゆえ、職業小分類を尋ねているデータとマッチングすることで、個人が持つ（と職業上は期待される）スキルを知ることができるようになります。

O-NETで尋ねられている項目は比較可能形式といえど、厳密な意味では比較可能ではありません。というのも、尋ねている項目ごとに頻度や重要度、比率などその中身が異なるためです。

表1. O-NETの調査内容と各選択肢のタイプ

| 調査内容 | 選択肢のタイプ |
| --- | --- |
| 職業興味 | 合致度 |
| 仕事価値観 | 満足感 |
| スキル | レベル |
| 知識 | 重要度 |
| 仕事の性質 | 頻度A
|  | 頻度B
|  | 重要度
|  | 責任の度合い
|  | その他 |
| 仕事の内容 | 重要度 |

もちろん、選択肢のタイプが異なることは回答者の負担減のために行われていることなので、それ自体はごくふつうなことですが、O-NETの使用においては複数の調査項目を合算して用いることがままあるため、結果が選択肢のタイプによって歪まないように分析者が調査内容横断的な各項目を比較可能にすることがあります。それが標準化です。

# 標準化の支配的アプローチ：Accemoglu and Autor

多くの研究では、Accemoglu and Autor（2011）の手続きに倣って標準化が行われています。それは以下2回の標準化を行います。

1. マッチング後に就業者数で重み付け標準化
2. 合算後に再標準化

1の手続きについては、主として2つの目的があります。①上述した通り、項目を統計的な意味で比較可能にする、②職業を1単位とした水準から、マッチングしたデータの分析単位を1単位とした水準に各種指標を変換する、です。②は重み付けとして行われます。今回は重み付けの話は割愛します。2の手続きは主として解釈のために行われます。すなわち、平均0、標準偏差1とならすことで、値の正負や量について解釈を容易にするためになします。逆にいえば、2を行わなかったとしても、統計的な表現としては等価なものが出力されます（1回目の標準化後にサンプルの追加や欠損が一切なかった場合は、です）。

# 標準化の実質的アプローチ

※ここからはほとんど悩みと、暫定的な結論です。誤りなどの指摘を歓迎します。

ここで、1の手続きでは標準化は2回、2の手続きでは1回を行うはずです。1の手続きの1回目を1-1、2回目を1-2とします。はじめに、1-1ではそれぞれの項目について標準化します。1-1の標準化を通じて、値の大小をなくし、標準偏差として表現する形式にします。0〜100の閾値をとる比率も、1〜7の値を取る重要度も、平均0標準偏差1として表現されます。おそらく、1-1だけで標準化を終え、合算に進むのは誤りです。なぜなら、統計量としては比較可能になっているけれども、項目間では比較可能になっていないためです。項目同士を比較可能、合算可能にするためには、さらにすべての項目を1度で標準化する必要があります。言い換えれば、複数列にまたがるスキル項目を1つの列に集約し、その列について標準化を行わなければならない、ということです。これが1-2に相当します。標準化後は列を分解します。1-1と1-2を通じて、尺度をならしつつ、項目を比較可能な形式に整えます。2回の標準化を通して、はじめて項目が合算可能になります。

問題関心次第ですが、合算後の指標は基本的に1列に集約して標準化してはいけません。それはなぜなら、指標の間で値が大きい（小さい）ということを表現してしまうためです。すなわち、「言語スキルは計算スキルより値が大きい（小さい）」といったような、指標間での値の大きさの話に帰着してしまうためです。いわゆる標準化回帰係数Bを考えてもらうと良いと思います。「どのスキル指標が最も大きいのか？」という問いでは良いのかもしれませんが、スキル水準についてとくに個人間・時代間などでの比較を行いたい場合は、余計な情報になってしまいます。したがって、合算後のスキル指標については指標ごとに標準化を行い、指標間の標準化は行わないべきでしょう。項目がすでに比較可能であり、二度目の標準化は解釈のために行われるというこれまでの話を踏まえれば、スキル指標は合算時点で比較可能な形式になっているはずです。

# 複数時点でのスキル指標

ところで、自分はスキル移転の研究をしています。転職の前後でスキルはどう変化するのか、ということを記述的に明らかにしようとしています。このとき、標準化はどのように行うべきでしょうか。

ポイントは複数時点の職業情報がある点です（簡単のため、前職と現職とします）。このとき、前職と現職それぞれで標準化してしまうと、やはり前職と現職とが比較可能になりません。今度は前職と現職とを1列としてマッチングを行います。各職業に紐づいた項目から、1-1をはじめます。そして、1-2では前職と現職とが1列になっている状態で、さらに項目を1列とします。person-yearデータならぬperson-occupation-itemデータのような状況です(!?)。もしパーソンイヤーデータすべての職業について行う場合は・・・、ご想像にお任せします。笑

# おわりに

O-NETは大きなポテンシャルを持つデータですが、自分自身取り扱いに苦労しています。こと標準化に関しては、やり方によっては結果を大きく変えてしまう危険性があるので、特に苦労しました。尺度の閾値の影響を取り除きつつ、厳密な意味で比較可能にすること、「項目同士」は比較可能にするけれども、「指標同士」は比較可能にしないこと、推定したい量を定義し、何と比較するのかを確定しておくことが、指標を取り扱う上では大事なのかなと思います。